name: Stop resources

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Which environment to deploy
        default: production
        options:
          - production
      confirm_stop_vpn_server:
        type: boolean
        description: Stop VPN Server?
        default: false
      aws_region:
        type: choice
        description: Region to deploy vpn server
        default: eu-west-2
        options:
          - eu-west-2
          - us-west-2
          - ap-northeast-2
          - ap-northeast-1
          - eu-central-1
          - eu-west-3

env:
  python_version: "3.10"

jobs:
  stop:
    if: github.actor == 'zcemycl'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ github.event.inputs.aws_region }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{env.python_version}}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awscli

      - name: Stop VPN Server
        if: ${{ github.event.inputs.confirm_stop_vpn_server == 'true' }}
        run: |
          instance_ids=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=*vpn-*" Name=instance-state-name,Values=running \
            --query "Reservations[].Instances[].InstanceId" --output text)
          for instance_id in $instance_ids; do
            net_id=$(aws ec2 describe-network-interfaces \
              --filters Name=attachment.instance-id,Values=$instance_id \
              --query "NetworkInterfaces[].NetworkInterfaceId" --output text)
            ass_id=$( aws ec2 describe-addresses \
              --filters  Name=network-interface-id,Values=$net_id \
              --query "Addresses[].AssociationId" --output text)
            allo_id=$( aws ec2 describe-addresses \
              --filters  Name=network-interface-id,Values=$net_id \
              --query "Addresses[].AllocationId" --output text)
            [ ! -z "$ass_id" ] && aws ec2 disassociate-address --association-id $ass_id
            sleep 5
            [ ! -z "$allo_id" ] && aws ec2 release-address --allocation-id $allo_id
            sleep 5
            aws ec2 stop-instances --instance-ids $instance_id
          done
